# Generated by Django 3.2.7 on 2022-04-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbr',
            field=models.CharField(default='', max_length=20, verbose_name='分类名缩写'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='分类名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='resume',
            field=models.TextField(default='', verbose_name='分类简介'),
            preserve_default=False,
        ),
    ]
