# Generated by Django 3.2.7 on 2022-04-23 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220419_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='resume',
            field=models.TextField(default='', verbose_name='服务简介'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category', verbose_name='服务分类'),
        ),
    ]
